version: '3'
services:
  web:
    build: .
    command: bash -c 'bundle exec jets server --host=0.0.0.0'
    volumes: 
      - .:/app
    ports:
      - 8888:8888
      - 3035:3035
    depends_on:
      - postgres
      - elasticsearch
    tty: true
    stdin_open: true

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_sf:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  postgres_sf:
    driver: local
  esdata01:
    driver: local
